rhbase_firewall_allow_services:
  - samba
  - ftp
samba_load_printers:
  - false
samba_netbios_name: files

rhbase_user_groups:
  - management
  - technical
  - sales
  - it

samba_shares:
  - name: management
    comment: ''
    write_list: +management
    valid_users: +management
    group: management
    directory_mode: "0770"
  - name: technical (software development)
    comment: ''
    write_list: +technical
    valid_users: +technical,+management,+sales,+it
    group: technical
  - name: sales
    comment: ''
    write_list: +sales
    valid_users: +sales,+management
    group: sales
  - name: it (system administration)
    comment: ''
    write_list: +it
    valid_users: +it,+management
    group: it
  - name: public
    comment: ''
    public: yes
    write_list: +users
    valid_users: +users
    setype: samba_share_t

samba_workgroup: avalon
