rhbase_firewall_allow_services:
  - samba
  - ftp
samba_load_printers:
  - false
samba_netbios_name: files

rhbase_user_groups:
  - management
  - technical
  - sales
  - it

samba_shares:
  - name: management
    comment: ''
    write_list: +management
    valid_users: +management
    group: management
    directory_mode: "0770"
  - name: technical (software development)
    comment: ''
    write_list: +technical
    valid_users: +technical
    group: technical
  - name: sales
    comment: ''
    write_list: +sales
    valid_users: +sales
    group: sales
  - name: it (system administration)
    comment: ''
    write_list: +it
    valid_users: +it
    group: it
  - name: public
    comment: ''
    write_list: +public
    valid_users: +public
    group: public
