rhbase_firewall_allow_services:
  - samba
  - ftp
samba_load_printers:
  - false
samba_netbios_name: files
samba_shares:
  - name: management
    comment: ''
    write_list: +management
    valid_users: +management
    group: management
    directory_mode: "0770"
