#Hier wordt de domein naam geconfigureerd
bind_zone_name: avalon.lan

#Hier wordt de ip-adres van de DNS server geconfigureerd
bind_zone_master_server_ip: 192.0.2.10

#Hier worden de  netwerken dat in de domein zitten geconfigureerd. In ons geval zijn er twee verschillende domeinen, namelijk 192.0.2.0 en 172.16.0.0
bind_zone_networks:
  - "192.0.2"
  - "172.16"

#Hier worden de namen van de dns servers in het domein geconfigureerd. In ons domein hebben we twee dns servers met de namen pu001 (DNS server) en pu002 (slave dns server)
bind_zone_name_servers:
  - pu001
  - pu002

#Hier geef je mee, naar welke interfaces er naar geluisterd moet worden. In ons geval moet er naar alle interfaces geluisterd worden.
bind_listen_ipv4:
  - any

#Hier geef je mee welke servers toegang hebben tot de DNS server. In ons geval hebben alle servers toegang.
bind_allow_query:
  - any

#Firewall configureren als DNS Server
rhbase_firewall_allow_services:
  - dns
