# site.yml
---
- hosts: pu004
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.httpd
    - bertvv.mariadb
    - bertvv.wordpress
#    - nbigot.ansible-fail2ban
    - memiah.fail2ban-wordpress


  pre_tasks:
    - name: Webserver private key kopieren
      copy:
        src: certificaten/device.key
        dest: /etc/pki/tls/private/ca.key
    - name: Web server certificaat kopieren
      copy:
        src: certificaten/device.crt
        dest: /etc/pki/tls/certs/ca.crt
- hosts: pu001
  sudo: true
  roles:
    - bertvv.rh-base
    - bertvv.bind
- hosts: pu002
  sudo: true
  roles:
    - bertvv.rh-base
    - bertvv.bind

- hosts: pr011
  sudo: true
  roles:
    - bertvv.rh-base
    - bertvv.samba
    - bertvv.vsftpd


- hosts: pr001
  sudo: true
  roles:
    - bertvv.rh-base
    - bertvv.dhcp

#- acl:
#    path: /srv/shares/sales
#    entity: technical
#    etype: group
#    permissions: r
#    state: present
